version: "3.9"

services:
  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: traefik/whoami
    environment:
      WHOAMI_PORT_NUMBER: 8081
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)
      - traefik.http.services.whoami-service.loadbalancer.server.port=8081

  comments-tone:
    image: 142412772381.dkr.ecr.eu-west-1.amazonaws.com/prodigy-quesmed-comments:latest
    command: prodigy textcat.manual tone ./datasets/comments.jsonl --label negative,neutral,positive --exclusive
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.comments-tone.rule=Host(`comments-tone.localhost`)
        - traefik.http.services.comments-tone-service.loadbalancer.server.port=8080

  comments-emotion:
    image: 142412772381.dkr.ecr.eu-west-1.amazonaws.com/prodigy-quesmed-comments:latest
    command: prodigy textcat.manual emotion ./datasets/comments.jsonl --label sadness,joy,love,anger,fear,surprise --exclusive
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.comments-emotion.rule=Host(`comments-emotion.localhost`)
        - traefik.http.services.comments-emotion-service.loadbalancer.server.port=8080

  comments-theme:
    image: 142412772381.dkr.ecr.eu-west-1.amazonaws.com/prodigy-quesmed-comments:latest
    command: prodigy textcat.manual theme ./datasets/comments.jsonl --label educational,feedback,question,insulting,supporting,humour,frustration --exclusive
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.comments-theme.rule=Host(`comments-theme.localhost`)
        - traefik.http.services.comments-theme-service.loadbalancer.server.port=8080
