version: "3.9"

services:
  comments-tone:
    image: prodigy-quesmed-comments
    container_name: comments-tone
    command: prodigy textcat.manual tone ./datasets/tone.jsonl --label negative,neutral,positive --exclusive
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - pg-network

  comments-emotion:
    image: prodigy-quesmed-comments
    container_name: comments-emotion
    command: prodigy textcat.manual emotion ./datasets/emotion.jsonl --label sadness,joy,love,anger,fear,surprise --exclusive
    ports:
      - 8081:8080
    depends_on:
      - postgres
    networks:
      - pg-network

  comments-theme:
    image: prodigy-quesmed-comments
    container_name: comments-theme
    command: prodigy textcat.manual theme ./datasets/comments.jsonl --label educational,feedback,question,insulting,supporting,humour,frustration
    ports:
      - 8082:8080
    depends_on:
      - postgres
    networks:
      - pg-network

  postgres:
    image: postgres:16-alpine
    container_name: pg-quesmed-comments
    restart: unless-stopped
    env_file: .env
    ports:
      - target: 5432
        published: 5432
    networks:
      - pg-network
    volumes:
      - pgdata16:/var/lib/postgresql/data

volumes:
  pgdata16:

networks:
  pg-network:
    driver: bridge
