version: "3.9"

services:
  tone:
    image: 142412772381.dkr.ecr.eu-west-1.amazonaws.com/prodigy-quesmed-comments:latest
    command: prodigy textcat.manual tone ./datasets/comments.jsonl --label negative,neutral,positive --exclusive
    networks:
      - traefik-proxy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.comments-tone.rule=Host(`comments-tone.quesmed.com`)
        - traefik.http.routers.comments-tone.tls=true
        - traefik.http.routers.comments-tone.middlewares=https_redirect@file
        - traefik.http.services.comments-tone-service.loadbalancer.server.port=8080

  emotion:
    image: 142412772381.dkr.ecr.eu-west-1.amazonaws.com/prodigy-quesmed-comments:latest
    command: prodigy textcat.manual emotion ./datasets/comments.jsonl --label sadness,joy,love,anger,fear,surprise --exclusive
    networks:
      - traefik-proxy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.comments-emotion.rule=Host(`comments-emotion.quesmed.com`)
        - traefik.http.routers.comments-emotion.tls=true
        - traefik.http.routers.comments-emotion.middlewares=https_redirect@file
        - traefik.http.services.comments-emotion-service.loadbalancer.server.port=8080

  theme:
    image: 142412772381.dkr.ecr.eu-west-1.amazonaws.com/prodigy-quesmed-comments:latest
    command: prodigy textcat.manual theme ./datasets/comments.jsonl --label educational,feedback,question,insulting,supporting,humour,frustration
    networks:
      - traefik-proxy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.comments-theme.rule=Host(`comments-theme.quesmed.com`)
        - traefik.http.routers.comments-theme.tls=true
        - traefik.http.routers.comments-theme.middlewares=https_redirect@file
        - traefik.http.services.comments-theme-service.loadbalancer.server.port=8080

networks:
  traefik-proxy:
    external: true
